### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by yungdec** [yungdec/24hr-vaporwave#1]
so this will be a thing soon if I get around to it soon,

hopefully i'll add some shit to this in a couple days.

xoxo
dec.

**Comment by SEAPUNK** [comment]
what'll you add to it

**Comment by yungdec** [comment]
some shit

**Comment by SEAPUNK** [comment]
what's some shit

**Comment by yungdec** [comment]
thinking emoji

**Comment by SEAPUNK** [comment]
i would add a pr to add a thinking emoji but github wont let me because the repository is empty

**Comment by yungdec** [comment]
tbh the reason i only started using github is because i never figured out how to work it :thought_balloon:

**Comment by SEAPUNK** [comment]
woprk it girl

**Comment by yungdec** [comment]
mf why u still here

**Comment by SEAPUNK** [comment]
waiting

**Comment by yungdec** [comment]
i should actually make this thing

**Comment by SEAPUNK** [comment]
``` bash
$ make thing
```

**Comment by yungdec** [comment]
one day

**Comment by SEAPUNK** [comment]
boo

**Comment by yungdec** [comment]
away

**Comment by SEAPUNK** [comment]
begone
